# Generated by Django 4.0.4 on 2022-05-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_alter_author_quote'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table=None,
        ),
        migrations.AlterModelTable(
            name='quote',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
    ]
