# Generated by Django 4.0.4 on 2022-05-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_alter_author_table_alter_quote_table_alter_tag_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='authors',
        ),
        migrations.AlterModelTable(
            name='quote',
            table='quotes',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tags',
        ),
    ]
