# Generated by Django 4.0.4 on 2022-05-10 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_alter_author_table_alter_quote_table_alter_tag_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quote.quote'),
        ),
    ]
