# Generated by Django 4.0.4 on 2022-05-10 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quote', '0005_alter_author_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='author',
        ),
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='quote.author'),
        ),
        migrations.AddField(
            model_name='quote',
            name='tag',
            field=models.ManyToManyField(to='quote.tag'),
        ),
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
