# Generated by Django 4.0.4 on 2022-05-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0013_alter_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True, unique=True),
        ),
    ]
