# Generated by Django 4.0.4 on 2022-05-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0014_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
